### ISSUE TITLE
kirigami module missing?

### ISSUE THREAD

**Issue by wkitty42** [olib14/thermalmonitor#1]
`
file:///home/myuser/.local/share/plasma/plasmoids/org.kde.olib.thermalmonitor/contents/ui/main.qml:12:1: module "org.kde.kirigami" version 2.20 is not installed
`
i get the above when i try to use this widget instead of the original by kotelnik...

Kubuntu 22.04.4 LTS
KDE Plasma : 5.24.7
KDE Frameworks : 5.92.0
Qt : 5.15.3
Graphics Platform : X11
GPU : GeForce RTX 2060

i did load muon and search for kirigami... found a couple seemingly related to mobile use... installed kirigami-gallery with no luck then realized it is version 21.12.3-0ubuntu1 and not the 2.20 the error message is complaining about not finding...

also noted the error message talking about org.kde.kirigami but i have qml-module-org-kde-kirigami2 version 5.92.0-0ubuntu2 installed by default i think...

**Comment by olib14** [comment]
The KF5 version of the plasmoid requires KDE Frameworks 5.95, which provides Kirigami 2.20.

What you can do is replace any instances (in the plasmoid's qml files) of:

```qml
import org.kde.kirigami 2.20 as Kirigami
```

with:

```qml
import org.kde.kirigami 2.19 as Kirigami
```

This should work fine, though I won't be releasing any new versions of the plasmoid.

The files, as noted in the error, were installed to `/home/myuser/.local/share/plasma/plasmoids/org.kde.olib.thermalmonitor/contents/ui/`.

**Comment by wkitty42** [comment]
thank you... i did change the number from 2.20 to 2.19 in 5 files... rebooted and immediately saw a much better thermometer image on the widget... however, adding a new one to the desktop and trying to configure it shows a blank Sensors page...

i appreciate the response and attempt to fix but apparently it isn't for my system... thank you for trying!

**Comment by olib14** [comment]
Sorry to hear it - feel free to give it another go if you update to the next LTS.

**Comment by wkitty42** [comment]
> Sorry to hear it - feel free to give it another go if you update to the next LTS.

thanks... i likely will try it again when i next update...
